from .base import Strategy, SignalFrame
from .baseline_momentum import MomentumRotation, MovingAverageCrossover, BuyAndHold
from .mean_reversion import MeanReversionAfterDrop
from .event_driven import EventDrivenStrategy
from .ml_signal import MLRankerStrategy
from .extended2 import (
    # Trend Part 2
    MACDCrossoverStrategy,
    BollingerBandBreakout,
    KeltnerChannelBreakout,
    SupertrendStrategy,
    IchimokuCloudProxy,
    ParabolicSARProxy,
    ADXTrendFollowing,
    HeikinAshiTrend,
    FiftyTwoWeekHighMomentum,
    OpeningRangeBreakoutProxy,
    # Mean Reversion Part 2
    ZScoreMeanReversion,
    StochasticOscillatorReversion,
    CCIMeanReversion,
    VWAPReversionProxy,
    ShortTermReversal,
    GapFillStrategy,
    ETFMeanReversion,
    # Factor Part 2
    ValueFactorStrategy,
    SizeFactorStrategy,
    QualityFactorStrategy,
    ProfitabilityFactor,
    InvestmentFactor,
    CarryFactorStrategy,
    QualityMinusJunk,
    MultiFactor5,
    MarketNeutralMomentum,
    EqualRiskContribution,
    HierarchicalRiskParity,
    ManagedFuturesCTA,
    GlobalMacroTrend,
    # Arb / relative value
    IndexRebalanceMomentum,
    MergerArbitrageProxy,
    VolatilityArbitrage,
    DispersionTrading,
    # ML / event
    EarningsMomentumStrategy,
    PostEarningsDrift,
    NewsSentimentSignal,
    RandomForestSignal,
    GradientBoostingSignal,
    EnsembleSignalVoting,
    AnomalyDetectionStrategy,
    SHAPFeatureAttributionStrategy,
    ThompsonSamplingRL,
    GeneticMomentumSearch,
    # Additional composites
    RelativeStrengthRotation,
    VolatilityTargetingStrategy,
    LongShortEquityFactor,
    CalendarSpreadMomentum,
    AnalystRevisionProxy,
)
from .extended import (
    # Trend-following
    DualMomentumAbsolute,
    TrendFollowingEMA,
    TripleMovingAverageCrossover,
    PriceMomentumWithVolFilter,
    BreakoutStrategy,
    TurtleTrendFollowing,
    AdaptiveTrendWithRegime,
    RateOfChangeMomentum,
    WeeklyMomentumRotation,
    TimeSeriesMomentum,
    # Mean reversion
    RSIOversoldBounce,
    BollingerBandReversion,
    OvernightGapFill,
    SMACrossoverMeanReversion,
    HighFrequencyMeanReversion,
    DrawdownBounce,
    LowRSIMomentumCombo,
    # Volatility / risk
    MinimumVolatilityPortfolio,
    VolatilityBreakout,
    RiskParityVolTargeting,
    VIXContrarianStrategy,
    ATRPositionSizing,
    # Factor combinations
    MomentumQualityCombo,
    MomentumValueMix,
    LowVolMomentumFactor,
    SectorRotationProxy,
    TrendPlusMeanReversionBlend,
    CrossSectionalRankZ,
    # Regime / macro
    RegimeSwitchingMomentum,
    HighVolRegimeCash,
    TrendStrengthFilter,
    MarketCapWeightedMomentum,
    YieldCurveAdaptive,
    # Statistical / pairs
    RelativeMomentumSpread,
    CrossSectionalReversal,
    VarianceRatioPairs,
    MomentumAnomalyFilter,
    # Novel composites
    MomentumWithVolumeSurge,
    AccelerationMomentum,
    AdaptiveRegimeBlend,
    FractalMomentumStrategy,
    VolatilityNormalisedMomentum,
    EventDrivenMomentumConfluence,
    ContraMomentumHighVolatility,
    LiquidityWeightedMomentum,
    MultiHoldPeriodBlend,
)

# Registry: name → constructor (no-arg lambda)
STRATEGY_REGISTRY: dict[str, object] = {
    # Original 4
    "buy_and_hold": BuyAndHold,
    "ma_crossover": MovingAverageCrossover,
    "momentum_rotation": MomentumRotation,
    "mean_reversion": MeanReversionAfterDrop,
    "event_driven": EventDrivenStrategy,
    "ml_ranker": MLRankerStrategy,
    # Trend
    "dual_momentum_absolute": DualMomentumAbsolute,
    "trend_ema_cross": TrendFollowingEMA,
    "triple_ma": TripleMovingAverageCrossover,
    "mom_vol_filter": PriceMomentumWithVolFilter,
    "breakout_20d_high": BreakoutStrategy,
    "turtle_donchian": TurtleTrendFollowing,
    "adaptive_trend_regime": AdaptiveTrendWithRegime,
    "roc_momentum": RateOfChangeMomentum,
    "weekly_mom_rotation": WeeklyMomentumRotation,
    "time_series_momentum": TimeSeriesMomentum,
    # Mean reversion
    "rsi_oversold_bounce": RSIOversoldBounce,
    "bollinger_reversion": BollingerBandReversion,
    "overnight_gap_fill": OvernightGapFill,
    "sma_stretch_reversion": SMACrossoverMeanReversion,
    "hf_mean_reversion": HighFrequencyMeanReversion,
    "drawdown_bounce": DrawdownBounce,
    "low_rsi_mom_combo": LowRSIMomentumCombo,
    # Volatility
    "min_vol_portfolio": MinimumVolatilityPortfolio,
    "vol_breakout": VolatilityBreakout,
    "risk_parity_vol_target": RiskParityVolTargeting,
    "vix_contrarian": VIXContrarianStrategy,
    "atr_position_sizing": ATRPositionSizing,
    # Factor combos
    "mom_quality_combo": MomentumQualityCombo,
    "momentum_value_mix": MomentumValueMix,
    "low_vol_momentum": LowVolMomentumFactor,
    "sector_rotation_proxy": SectorRotationProxy,
    "trend_plus_reversion": TrendPlusMeanReversionBlend,
    "cross_sectional_rankz": CrossSectionalRankZ,
    # Regime / macro
    "regime_switching_momentum": RegimeSwitchingMomentum,
    "high_vol_cash": HighVolRegimeCash,
    "trend_strength_filter": TrendStrengthFilter,
    "mkt_cap_weighted_mom": MarketCapWeightedMomentum,
    "yield_curve_adaptive": YieldCurveAdaptive,
    # Statistical
    "relative_momentum_spread": RelativeMomentumSpread,
    "cross_sectional_reversal": CrossSectionalReversal,
    "variance_ratio_pairs": VarianceRatioPairs,
    "momentum_anomaly_filter": MomentumAnomalyFilter,
    # Novel composites
    "momentum_volume_surge": MomentumWithVolumeSurge,
    "acceleration_momentum": AccelerationMomentum,
    "adaptive_regime_blend": AdaptiveRegimeBlend,
    "fractal_momentum": FractalMomentumStrategy,
    "vol_normalised_momentum": VolatilityNormalisedMomentum,
    "event_momentum_confluence": EventDrivenMomentumConfluence,
    "contra_momentum_high_vol": ContraMomentumHighVolatility,
    "liquidity_weighted_momentum": LiquidityWeightedMomentum,
    "multi_hold_blend": MultiHoldPeriodBlend,
    # ── Extended Part 2 ──────────────────────────────────────────────────────
    # Trend Part 2
    "macd_crossover": MACDCrossoverStrategy,
    "bb_breakout": BollingerBandBreakout,
    "keltner_breakout": KeltnerChannelBreakout,
    "supertrend": SupertrendStrategy,
    "ichimoku_proxy": IchimokuCloudProxy,
    "parabolic_sar_proxy": ParabolicSARProxy,
    "adx_trend": ADXTrendFollowing,
    "heikin_ashi_trend": HeikinAshiTrend,
    "52wk_high_momentum": FiftyTwoWeekHighMomentum,
    "orb_proxy": OpeningRangeBreakoutProxy,
    # Mean Reversion Part 2
    "zscore_reversion": ZScoreMeanReversion,
    "stochastic_reversion": StochasticOscillatorReversion,
    "cci_reversion": CCIMeanReversion,
    "vwap_reversion": VWAPReversionProxy,
    "short_term_reversal": ShortTermReversal,
    "gap_fill": GapFillStrategy,
    "etf_mean_reversion": ETFMeanReversion,
    # Factor Part 2
    "value_factor": ValueFactorStrategy,
    "size_factor": SizeFactorStrategy,
    "quality_factor": QualityFactorStrategy,
    "profitability_factor": ProfitabilityFactor,
    "investment_factor": InvestmentFactor,
    "carry_factor": CarryFactorStrategy,
    "quality_minus_junk": QualityMinusJunk,
    "multi_factor_5": MultiFactor5,
    "market_neutral_momentum": MarketNeutralMomentum,
    "equal_risk_contribution": EqualRiskContribution,
    "hrp": HierarchicalRiskParity,
    "managed_futures_cta": ManagedFuturesCTA,
    "global_macro_trend": GlobalMacroTrend,
    # Arb / relative value
    "index_rebalance_arb": IndexRebalanceMomentum,
    "merger_arb_proxy": MergerArbitrageProxy,
    "vol_arbitrage": VolatilityArbitrage,
    "dispersion_trading": DispersionTrading,
    # ML / event
    "earnings_momentum": EarningsMomentumStrategy,
    "pead": PostEarningsDrift,
    "news_sentiment": NewsSentimentSignal,
    "random_forest_signal": RandomForestSignal,
    "gradient_boosting_signal": GradientBoostingSignal,
    "ensemble_voting": EnsembleSignalVoting,
    "anomaly_detection": AnomalyDetectionStrategy,
    "shap_signal": SHAPFeatureAttributionStrategy,
    "thompson_sampling_rl": ThompsonSamplingRL,
    "genetic_momentum": GeneticMomentumSearch,
    # Additional composites
    "relative_strength_rotation": RelativeStrengthRotation,
    "vol_targeting": VolatilityTargetingStrategy,
    "long_short_equity": LongShortEquityFactor,
    "calendar_spread_momentum": CalendarSpreadMomentum,
    "analyst_revision_proxy": AnalystRevisionProxy,
}

__all__ = [
    "Strategy", "SignalFrame",
    "STRATEGY_REGISTRY",
    # Original
    "BuyAndHold", "MovingAverageCrossover", "MomentumRotation",
    "MeanReversionAfterDrop", "EventDrivenStrategy", "MLRankerStrategy",
    # Extended Part 1
    "DualMomentumAbsolute", "TrendFollowingEMA", "TripleMovingAverageCrossover",
    "PriceMomentumWithVolFilter", "BreakoutStrategy", "TurtleTrendFollowing",
    "AdaptiveTrendWithRegime", "RateOfChangeMomentum", "WeeklyMomentumRotation",
    "TimeSeriesMomentum", "RSIOversoldBounce", "BollingerBandReversion",
    "OvernightGapFill", "SMACrossoverMeanReversion", "HighFrequencyMeanReversion",
    "DrawdownBounce", "LowRSIMomentumCombo", "MinimumVolatilityPortfolio",
    "VolatilityBreakout", "RiskParityVolTargeting", "VIXContrarianStrategy",
    "ATRPositionSizing", "MomentumQualityCombo", "MomentumValueMix",
    "LowVolMomentumFactor", "SectorRotationProxy", "TrendPlusMeanReversionBlend",
    "CrossSectionalRankZ", "RegimeSwitchingMomentum", "HighVolRegimeCash",
    "TrendStrengthFilter", "MarketCapWeightedMomentum", "YieldCurveAdaptive",
    "RelativeMomentumSpread", "CrossSectionalReversal", "VarianceRatioPairs",
    "MomentumAnomalyFilter", "MomentumWithVolumeSurge", "AccelerationMomentum",
    "AdaptiveRegimeBlend", "FractalMomentumStrategy", "VolatilityNormalisedMomentum",
    "EventDrivenMomentumConfluence", "ContraMomentumHighVolatility",
    "LiquidityWeightedMomentum", "MultiHoldPeriodBlend",
    # Extended Part 2
    "MACDCrossoverStrategy", "BollingerBandBreakout", "KeltnerChannelBreakout",
    "SupertrendStrategy", "IchimokuCloudProxy", "ParabolicSARProxy",
    "ADXTrendFollowing", "HeikinAshiTrend", "FiftyTwoWeekHighMomentum",
    "OpeningRangeBreakoutProxy", "ZScoreMeanReversion", "StochasticOscillatorReversion",
    "CCIMeanReversion", "VWAPReversionProxy", "ShortTermReversal",
    "GapFillStrategy", "ETFMeanReversion", "ValueFactorStrategy",
    "SizeFactorStrategy", "QualityFactorStrategy", "ProfitabilityFactor",
    "InvestmentFactor", "CarryFactorStrategy", "QualityMinusJunk",
    "MultiFactor5", "MarketNeutralMomentum", "EqualRiskContribution",
    "HierarchicalRiskParity", "ManagedFuturesCTA", "GlobalMacroTrend",
    "IndexRebalanceMomentum", "MergerArbitrageProxy", "VolatilityArbitrage",
    "DispersionTrading", "EarningsMomentumStrategy", "PostEarningsDrift",
    "NewsSentimentSignal", "RandomForestSignal", "GradientBoostingSignal",
    "EnsembleSignalVoting", "AnomalyDetectionStrategy", "SHAPFeatureAttributionStrategy",
    "ThompsonSamplingRL", "GeneticMomentumSearch",
    "RelativeStrengthRotation", "VolatilityTargetingStrategy", "LongShortEquityFactor",
    "CalendarSpreadMomentum", "AnalystRevisionProxy",
]
